version: 2

sources:
   # This should match the schema name where your tables are located
  - name: "{{ target.schema }}"
    tables:
      - name: alkis_parcels
      - name: alkis_buildings
      - name: xplannung
